name: Deploy to GitHub Pages

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Convert PHP to HTML
        run: |
          # Create output directory
          mkdir -p dist
          
          # Copy images directory
          cp -r images dist/
          
          # Convert index.php to index.html
          php -f index.php > dist/index.html
          
          # Convert other PHP files if they exist
          if [ -f "about.php" ]; then
            php -f about.php > dist/about.html
          fi
          
          if [ -f "shop.php" ]; then
            php -f shop.php > dist/shop.html
          fi
          
          if [ -f "register.php" ]; then
            php -f register.php > dist/register.html
          fi
          
          if [ -f "login.php" ]; then
            php -f login.php > dist/login.html
          fi
          
          if [ -f "agb.php" ]; then
            php -f agb.php > dist/agb.html
          fi

      - name: Fix HTML links
        run: |
          # Replace .php links with .html in all HTML files
          find dist -name "*.html" -type f -exec sed -i 's/href="[^"]*\.php"/href="&"/g; s/\.php"/.html"/g' {} \;
          find dist -name "*.html" -type f -exec sed -i 's/action="[^"]*\.php"/action="&"/g; s/\.php"/.html"/g' {} \;

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
