name: Deploy to GitHub Pages

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Convert PHP to HTML and copy assets
        run: |
          # Create output directory
          mkdir -p dist
          
          # Copy images directory
          if [ -d "images" ]; then
            cp -r images dist/
          fi
          
          # Copy PHP files as HTML (since they now contain static content)
          if [ -f "index.php" ]; then
            cp index.php dist/index.html
          fi
          
          if [ -f "about.php" ]; then
            cp about.php dist/about.html
          fi
          
          if [ -f "shop.php" ]; then
            cp shop.php dist/shop.html
          fi
          
          if [ -f "register.php" ]; then
            cp register.php dist/register.html
          fi
          
          if [ -f "login.php" ]; then
            cp login.php dist/login.html
          fi
          
          if [ -f "agb.php" ]; then
            cp agb.php dist/agb.html
          fi

      - name: Fix remaining PHP tags and links
        run: |
          # Remove any remaining PHP opening/closing tags
          find dist -name "*.html" -type f -exec sed -i 's/<?php[^>]*>//g' {} \;
          find dist -name "*.html" -type f -exec sed -i 's/?>//g' {} \;
          
          # Ensure all links point to .html files
          find dist -name "*.html" -type f -exec sed -i 's/href="\([^"]*\)\.php"/href="\1.html"/g' {} \;
          find dist -name "*.html" -type f -exec sed -i 's/action="\([^"]*\)\.php"/action="\1.html"/g' {} \;
          
          # Debug: Show what files were created
          echo "Created files:"
          ls -la dist/
          echo "Sample content from index.html:"
          head -10 dist/index.html || true

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4